### ISSUE TITLE
Not working on VPS

### ISSUE THREAD

**Issue by TH3AL3X** [bman46/InstagramEmbedDiscordBot#3]
Instagram have a detection of IP, so if is not a residential IP you can't do a request to his API, I tried to solve it on my own, but I have not succeeded, I hope you find a solution, since no one is going to put the bot on your local computer 24/7

**Comment by bman46** [comment]
Interesting. I haven't tried to spin it up in the cloud yet but I'll have to try it out. Currently I just run it in my homelab.

**Comment by bman46** [comment]
I just tested it out on azure and it does require a login to access the page with the content, however, I was able to find a free proxy that allowed me to circumvent Instagram's IP block. For now, you can set up a system wide proxy on the OS and the bot will work fine. Eventually I will probably build a proxy option into the config file.

**Comment by bman46** [comment]
Added the proxy option in. It is the only way that I found to bypass the IP restrictions so far.
