### ISSUE TITLE
"Sorry, Something went wrong..."

### ISSUE THREAD

**Issue by moxwel** [bman46/InstagramEmbedDiscordBot#4]
Recently, the bot is sending that message every time we sent an Instagram link.

![image](https://user-images.githubusercontent.com/49621788/131445273-8a975a6e-9cb9-444a-8f3a-bda2f137ed83.png)

This error was not happening some days ago.

**Comment by bman46** [comment]
I have noticed the error and I'll try to work on it when I get the time. One of the major issues that is causing this is Facebook's removal of OpenGraph from Instagram.

**Comment by moxwel** [comment]
This is unfortunate. Well, hoping Facebook fixes it... Thanks for the clarification!

**Comment by bman46** [comment]
Had some free time today and was able to fix the bot. Please note that if you are hosting it now requires an instagram account. Please let me know if you notice any issue with it.

**Comment by moxwel** [comment]
Works well!
