### ISSUE TITLE
System.NullReferenceException on checking Subscribed List

### ISSUE THREAD

**Issue by angkanalog** [bman46/InstagramEmbedDiscordBot#44]
Bot crashed when checking deleted instagram account. and need to be restarted everytime `/subscribed` or checking new posts until account record deleted in mongodb. (example InstagramID 2248802466962)

**Comment by bman46** [comment]
Cannot replicate in the latest version. Ensure that you are running the latest version. I attempted to replicate the issue using the following directions: `if you want to recreate it just /subscribe kevin, and then search InstagramID: "3" and change it to "48802466962". then just /subscribed it will dm you the error, it wont crash (no need to restart) but the command is broken (haven't test the timed getting new posts)` The timed post mechanism in the latest version will automatically remove the account and the `/subscribed` and `/unsubscribe` command will show `Deleted Account`.
