### ISSUE TITLE
startfile missed

### ISSUE THREAD

**Issue by mulano1977** [bman46/InstagramEmbedDiscordBot#53]
The instructions say: "find the file named `Instagram Reels Bot` with no extensions". Unfortunately, there is no such file without an extension.

**Comment by bman46** [comment]
Please do an `ls` to show all of the files in the folder, then paste the list here.

**Comment by mulano1977** [comment]
argh.... i downloaded the source code. pure stupidity of me. please delete this immediately. it's embarrassing xD you shouldn't work overtired -.-

**Comment by bman46** [comment]
Ok, no worries.
