### ISSUE TITLE
Remove "Delete Message"

### ISSUE THREAD

**Issue by frorayz** [bman46/InstagramEmbedDiscordBot#56]
Removing the delete message button.

**Comment by angkanalog** [comment]
you can comment/remove this 2 line : https://github.com/bman46/InstagramEmbedDiscordBot/blob/7fa163c7feb73b62a39fdef90a8d784e258c9480/Instagram%20Reels%20Bot/Helpers/Builders/IGComponentBuilder.cs#L77
https://github.com/bman46/InstagramEmbedDiscordBot/blob/7fa163c7feb73b62a39fdef90a8d784e258c9480/Instagram%20Reels%20Bot/Helpers/Builders/IGComponentBuilder.cs#L104

currently there's no option to remove it via config.json

**Comment by bman46** [comment]
Option added in the latest update. see PR #57
