### ISSUE TITLE
what is the run cmd?

### ISSUE THREAD

**Issue by ehsansayrafi** [bman46/InstagramEmbedDiscordBot#6]
for ex , node.js is usually npm start 
what is it for c#?

**Comment by bman46** [comment]
Javascript is an interpreted language, so it doesn't require the program to be complied. For C#, which is a compiled language, you need to run it through a compiler to get an executable file (.exe or other OS equivalent) so you can run it as you would any other desktop program. 

I would suggest you download [Visual Studio](https://visualstudio.microsoft.com/) and compile it from there as it is the easiest. Opening the .sln file will open the project in visual studio.

If you would prefer command line, you can install the [dotnet CLI tools](https://docs.microsoft.com/en-us/dotnet/core/tools/) and use the `dotnet build "Instagram Reels Bot.sln"` command.
