### ISSUE TITLE
Error: Collective file size exceeds the max file size of 8388608 bytes in that guild! (Parameter 'attachments')

### ISSUE THREAD

**Issue by kevinnocom** [bman46/InstagramEmbedDiscordBot#69]
I am receiving the following error with longer reels. Images and shorter reels seem to work fine.

`Collective file size exceeds the max file size of 8388608 bytes in that guild! (Parameter 'attachments')`

**Comment by Twooearly** [comment]
It says that the Instagram Reel or Video you are trying to send in a Discord chat exceeds the Discord File upload Size. The Bot cant upload files bigger than that size.

**Comment by bman46** [comment]
Fix will be released in the next update.
