### ISSUE TITLE
After posting embed, an error posts

### ISSUE THREAD

**Issue by futurepro62** [bman46/InstagramEmbedDiscordBot#7]
After posting the embed, the bot posts an error each time.
![Screenshot_20211111-211429_Discord](https://user-images.githubusercontent.com/94158500/141413588-75fa6469-a5ad-4d23-96af-a48caae1b9e6.jpg)

**Comment by bman46** [comment]
After investigating, I believe that this is caused by a lack of permissions to disable embeds on the sender's message. I have updated the code and will let you know when its deployed to the bot.

**Comment by futurepro62** [comment]
Excellent. Thanks for the quick response!

**Comment by bman46** [comment]
Just released the fix to the bot. Let me know if it is still occurring. @futurepro62

**Comment by futurepro62** [comment]
Looks good now. Thanks again!

**Comment by bman46** [comment]
No problem!

**Comment by bman46** [comment]
Also, just for reference, you may want to give the bot permission to `Manage Messages` as it will suppress the automatic embeds from discord when you paste an instagram link in the chat. This will prevent the content from showing up twice (once from the bot and once from the user's message).

**Comment by futurepro62** [comment]
Oh, I will definitely do that. Thanks for the tip.
