### ISSUE TITLE
Carousel Post

### ISSUE THREAD

**Issue by Core-Coder** [bman46/InstagramEmbedDiscordBot#9]
Hey, Thanks for making this awesome discord bot. It's so helpful for us.

I just wanna suggest to see carousel post on discord too for new feature. It would be less time consuming for us if you could make this.

Once again thank you for developing this awesome bot. Keep Working on it!

**Comment by bman46** [comment]
Thanks for the suggestion!
I have been considering adding this for awhile; but in order to implement it, i would like to use slash commands to allow a user to define a specific picture/video or range of pictures/videos in the carousel. Unfortunately, Discord.net doesn't support slash commands yet, although they are expected to release them soon.

**Comment by Core-Coder** [comment]
Ahhhh ic, can't wait for it to be release soon! Keep up!

**Comment by bman46** [comment]
I'm going to leave this open until I update the bot.

**Comment by Core-Coder** [comment]
> I'm going to leave this open until I update the bot.

Sure

**Comment by bman46** [comment]
Just finished writing the code for this. Will release to the bot in the next update, would like to add a few more commands and test it more before then.

**Comment by bman46** [comment]
The update has been released to bot. use `/link url index` to select an image in a carousel. Also, the bot may need to be re-invited to the server for permission to use slash commands. Please, let me know if you have any issues.

**Comment by Core-Coder** [comment]
In my problem i use the slash or not it always show the first slide of carousel.

**Comment by bman46** [comment]
You need to use the index parameter in the slash command to select the slide number. Otherwise, it will default to the first one.

![image](https://user-images.githubusercontent.com/10489031/147387064-3565f4a0-83e1-4846-8191-1173b6235808.jpeg)

**Comment by Core-Coder** [comment]
> You need to use the index parameter in the slash command to select the slide number. Otherwise, it will default to the first one.
> 
> ![image](https://user-images.githubusercontent.com/10489031/147387064-3565f4a0-83e1-4846-8191-1173b6235808.jpeg) In this example I'm selecting the second image in the carousel.

oh wow although its kinda complicated, but it works! I don't know that you need to write link after the slash and the index : 2 too.

Good job man.

**Comment by bman46** [comment]
Thanks! I'm looking to simplify it in the future; however, that's how discord has it set up for now.
